-- https://github.com/jolaleye/horizon-theme-vscode/blob/master/themes/horizon-italic.json
-- https://horizontheme.netlify.app/
-- https://github.com/jolaleye/horizon-theme-vscode

-- checkout dark horizon - https://vscodethemes.com/e/mcagampan.dark-horizon/dark-horizon

-- Horizon Italic theme for Neovim, converted from VSCode theme
-- Core Neovim UI highlight groups
vim.api.nvim_set_hl(0, 'Comment', { italic = true })
vim.api.nvim_set_hl(0, 'Keyword', { italic = true })

vim.api.nvim_set_hl(0, 'Normal', { fg = '#D5D8DA', bg = '#1C1E26' })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#D5D8DA', bg = '#232530' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#2E303E' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#576c7d' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#D5D8DA' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#F09483' })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = '#BBBBBB' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#E95678' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#3d4052' })
vim.api.nvim_set_hl(0, 'Search', { fg = '#72f1b8', reverse = true })
vim.api.nvim_set_hl(0, 'IncSearch', { reverse = true })
vim.api.nvim_set_hl(0, 'MatchParen', { bg = '#4d9375' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#D5D8DA', bg = '#1C1E26' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#D5D8DA', bg = '#1C1E26' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#1A1C23' })
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#D5D8DA', bg = '#1C1E26' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#D5D8DA', bg = '#1C1E26' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#1C1E26' })
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#D5D8DA', bg = '#232530' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#2E303E' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#6C6F93' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#6C6F93' })
vim.api.nvim_set_hl(0, 'WildMenu', { fg = '#D5D8DA', bg = '#2E303E' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#E95678' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#D5D8DA' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#D5D8DA' })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#2E303E' })
vim.api.nvim_set_hl(0, 'FoldColumn', { fg = '#D5D8DA' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#1C1E26' })
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = '#102922' })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = '#4d0914' })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = '#2E303E' })
vim.api.nvim_set_hl(0, 'DiffText', { fg = '#D5D8DA', bg = '#2E303E' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#F43E5C' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#faf18e' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#E95378' })
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#D5D8DA' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#E95378' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#E95378' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#B877DB', italic = true })
vim.api.nvim_set_hl(0, 'Preproc', { fg = '#B877DB', italic = true })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#2E303E' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { bg = '#232530' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#ff5544' })
vim.api.nvim_set_hl(0, 'Terminal', { fg = '#D5D8DA', bg = '#1C1E26' })

-- Git-specific highlight groups
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#27D797' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#2ee2fa' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#F43E5C' })
vim.api.nvim_set_hl(0, 'GitSignsCurrentLineBlame', { fg = '#666666' })

-- Diagnostic highlight groups
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#F43E5C' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#faf18e' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#6394bf' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#27D797' })

-- Neogit highlight groups
vim.api.nvim_set_hl(0, 'NeogitDiffAddHighlight', { bg = '#14342b' })
vim.api.nvim_set_hl(0, 'NeogitDiffDeleteHighlight', { bg = '#650d1b' })
vim.api.nvim_set_hl(0, 'NeogitDiffContextHighlight', { bg = '#1C1E26' })

-- Tree-sitter syntax highlight groups
vim.api.nvim_set_hl(0, '@comment', { fg = '#7e7e7e', italic = true })
vim.api.nvim_set_hl(0, '@punctuation', { fg = '#BBBBBB' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#E95678' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#BBBBBB' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#F09483' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#F09483' })
vim.api.nvim_set_hl(0, '@variable', { fg = '#E95678' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#FAC29A', italic = true })
vim.api.nvim_set_hl(0, '@function', { fg = '#3bf4fb' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#3bf4fb' })
vim.api.nvim_set_hl(0, '@function.method', { fg = '#3bf4fb' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#D5D8DA', italic = true })
vim.api.nvim_set_hl(0, '@tag', { fg = '#E95678' })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#F09483', italic = true })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#B877DB', italic = true })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#B877DB' })
vim.api.nvim_set_hl(0, '@type', { fg = '#FAC29A' })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#FAC29A' })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#FAC29A' })
vim.api.nvim_set_hl(0, '@string', { fg = '#ccc3be' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#3bf4fb' })
vim.api.nvim_set_hl(0, '@string.regex', { fg = '#F09483' })
vim.api.nvim_set_hl(0, '@property', { fg = '#E95678' })
vim.api.nvim_set_hl(0, '@number', { fg = '#F09483' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#F09483' })
vim.api.nvim_set_hl(0, '@text.title', { fg = '#E95678' })
vim.api.nvim_set_hl(0, '@text.quote', { fg = '#FAB795', italic = true })
vim.api.nvim_set_hl(0, '@text.literal', { fg = '#F09483' })
vim.api.nvim_set_hl(0, '@text.strong', { fg = '#B877DB', bold = true })
vim.api.nvim_set_hl(0, '@text.emphasis', { fg = '#3bf4fb', italic = true })
vim.api.nvim_set_hl(0, '@text.uri', { fg = '#FAB795' })
vim.api.nvim_set_hl(0, '@text.diff.add', { fg = '#09F7A0' })
vim.api.nvim_set_hl(0, '@text.diff.delete', { fg = '#F43E5C' })
vim.api.nvim_set_hl(0, '@error', { fg = '#F43E5C' })
vim.api.nvim_set_hl(0, '@attribute', { fg = '#F09483', italic = true })
vim.api.nvim_set_hl(0, '@label', { fg = '#E95678' })
vim.api.nvim_set_hl(0, '@include', { fg = '#B877DB', italic = true })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#FAC29A' })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#4c9a91', italic = true })
vim.api.nvim_set_hl(0, '@variable.tsx', { fg = '#4c9a91' })
vim.api.nvim_set_hl(0, '@variable.typescript', { fg = '#4c9a91' })
vim.api.nvim_set_hl(0, '@constant.numeric', { fg = '#F09483' })
vim.api.nvim_set_hl(0, '@module', { fg = '#FAC29A' })
vim.api.nvim_set_hl(0, '@tag.builtin', { fg = '#E95678' })
vim.api.nvim_set_hl(0, '@tag.delimiter.html', { fg = '#2ee2fa' })
vim.api.nvim_set_hl(0, '@tag.delimiter.tsx', { fg = '#2ee2fa' })
