-- Paddy Wolf Light Mode

vim.api.nvim_set_hl(0, 'Comment', { italic = true })
vim.api.nvim_set_hl(0, 'Keyword', { italic = true })

vim.api.nvim_set_hl(0, 'Normal', { fg = '#3d2f1f', bg = '#e6e1da' })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#3d2f1f', bg = '#f0ede8' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#f5f2ed' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#a19a95' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#6b7b28' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#1a7d5c' })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = '#7d5942' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#4a3226' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#e8d8e8' })
vim.api.nvim_set_hl(0, 'Search', { bg = '#2db889', fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'IncSearch', { reverse = true })
vim.api.nvim_set_hl(0, 'MatchParen', { bg = '#f5f2ed', reverse = true })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#52453b', bg = '#e6e1da' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#3d2f1f', bg = '#e8e2d8' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#3d2f1f' })
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#3d2f1f', bg = '#e8e2d8' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#2d1a0d', bg = '#e8e2d8' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#e8e2d8' })
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#2a2725', bg = '#f5f2ed' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#ddd9d2' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#93966c' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#93966c' })
vim.api.nvim_set_hl(0, 'WildMenu', { fg = '#3d2f1f', bg = '#92cd6e' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#3d2f1f' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#72677a' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#72677a' })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#ddd9d2' })
vim.api.nvim_set_hl(0, 'FoldColumn', { fg = '#3d2f1f' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#e6e1da' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#b8651d' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#4d8b83' })
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#52453b' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#5a9c15' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#3d2f1f' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#ddd9d2' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { bg = '#f0ede8' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#875956' })
vim.api.nvim_set_hl(0, 'Terminal', { fg = '#3d2f1f', bg = '#e8e2d8' })
vim.api.nvim_set_hl(0, 'UfoFoldedEllipsis', { bg = '#3d2f1f', fg = '#e8e2d8' })
vim.api.nvim_set_hl(0, 'WinSeparator', { fg = '#b3b3b3', bg = 'NONE' })

-- diff
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = '#d4edd6' })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = '#f2c2cb' })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = '#ddd9d2' })
vim.api.nvim_set_hl(0, 'DiffText', { fg = '#2a2725', bg = '#ddd9d2' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#d8495a' })

-- Git-specific highlight groups
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#1a7d5c' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#1bb8d1' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#d8495a' })
vim.api.nvim_set_hl(0, 'GitSignsCurrentLineBlame', { fg = '#999999' })

-- Diagnostic highlight groups
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#d8495a' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#b8651d' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#4d6b94' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#1a7d5c' })

-- Neogit highlight groups
vim.api.nvim_set_hl(0, 'NeogitDiffAddHighlight', { bg = '#d4edd6' })
vim.api.nvim_set_hl(0, 'NeogitDiffDeleteHighlight', { bg = '#f2c2cb' })
vim.api.nvim_set_hl(0, 'NeogitDiffContextHighlight', { bg = '#f0f0f0' })
vim.api.nvim_set_hl(0, 'NeogitSectionHeader', { fg = '#537990' })

-- treesitter
vim.api.nvim_set_hl(0, '@comment', { fg = '#a5aab0', italic = true })
vim.api.nvim_set_hl(0, '@comment.tsx', { fg = '#a5aab0', italic = true })
vim.api.nvim_set_hl(0, '@punctuation', { fg = '#7d5942' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#5e7990' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#9eb2bf' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#1a7d5c' })
vim.api.nvim_set_hl(0, '@constant.tsx', { fg = '#1a7d5c' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#1a7d5c' })
vim.api.nvim_set_hl(0, '@variable', { fg = '#4a3226' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#7c6d58', italic = true })
vim.api.nvim_set_hl(0, '@function', { fg = '#b5492f' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#a6412d' })
vim.api.nvim_set_hl(0, '@function.method', { fg = '#b8532c', italic = true, bold = false })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#a85c3a', italic = true })
vim.api.nvim_set_hl(0, '@tag', { fg = '#0d8a57', bold = false, underline = false })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#b86a34', italic = true })
vim.api.nvim_set_hl(0, '@tag.builtin.tsx', { fg = '#3c1772' })
vim.api.nvim_set_hl(0, '@punctuation.special.tsx', { fg = '#3c1772' })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#656a72', italic = true })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#8e4848', italic = true })
vim.api.nvim_set_hl(0, '@type', { fg = '#9d7723', italic = true, underline = false })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#925603', italic = true, underline = false })
vim.api.nvim_set_hl(0, '@type.tsx', { underline = false })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#858446' })
vim.api.nvim_set_hl(0, '@string', { fg = '#c26825' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#3d8271' })
vim.api.nvim_set_hl(0, '@string.regex', { fg = '#985289' })
vim.api.nvim_set_hl(0, '@property', { fg = '#9b6f10', bold = false })
vim.api.nvim_set_hl(0, '@number', { fg = '#ae5038' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#508912' })
vim.api.nvim_set_hl(0, '@text.title', { fg = '#b73333' })
vim.api.nvim_set_hl(0, '@text.quote', { fg = '#9a8c81', italic = true })
vim.api.nvim_set_hl(0, '@text.literal', { fg = '#778a43' })
vim.api.nvim_set_hl(0, '@text.strong', { fg = '#162128', bold = false })
vim.api.nvim_set_hl(0, '@text.emphasis', { fg = '#223d57', italic = true })
vim.api.nvim_set_hl(0, '@text.uri', { fg = '#39b36e', underline = false })
vim.api.nvim_set_hl(0, '@text.diff.add', { fg = '#3c1772' })
vim.api.nvim_set_hl(0, '@text.diff.delete', { fg = '#00ac8f' })
