-- https://images.vscodethemes.com/yile-ou.paddy-color-theme/p-wolf-go-preview-BFv0.svg
-- https://vscodethemes.com/e/yile-ou.paddy-color-theme/p-wolf
-- https://github.com/yl92/paddy-color-theme/blob/master/themes/default/Paddy-wolf-color-theme.json

-- Paddy Wolf

vim.api.nvim_set_hl(0, 'Comment', { italic = true })
vim.api.nvim_set_hl(0, 'Keyword', { italic = true })

vim.api.nvim_set_hl(0, 'Normal', { fg = '#dcbd9d', bg = '#0D0C0C' })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#dcbd9d', bg = '#292524' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#000000' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#5e5a58' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#9aaa47' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#2db889' })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = '#ac826e' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#e9cbb2' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#2a2e16' })
vim.api.nvim_set_hl(0, 'Search', { bg = '#72f1b8' })
vim.api.nvim_set_hl(0, 'IncSearch', { reverse = true })
vim.api.nvim_set_hl(0, 'MatchParen', { bg = '#000000' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#ad978d', bg = '#0D0C0C' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#dcbd9d', bg = '#221f1e' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#dcbd9d' })
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#dcbd9d', bg = '#221f1e' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#fcc9b5', bg = '#221f1e' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#221f1e' })
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#D5D8DA', bg = '#000000' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#22242e' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#6C6F93' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#6C6F93' })
vim.api.nvim_set_hl(0, 'WildMenu', { fg = '#dcbd9d', bg = '#6d9231' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#dcbd9d' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#8d8985' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#8d8985' })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#22242e' })
vim.api.nvim_set_hl(0, 'FoldColumn', { fg = '#dcbd9d' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#0D0C0C' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#e98842' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#73b4ac' })
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#ad978d' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#80bb2e' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#dcbd9d' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#22242e' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { bg = '#292524' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#b87e76' })
vim.api.nvim_set_hl(0, 'Terminal', { fg = '#dcbd9d', bg = '#221f1e' })
vim.api.nvim_set_hl(0, 'UfoFoldedEllipsis', { bg = '#dcbd9d', fg = '#221f1e' })

-- diff
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = '#102922' })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = '#4d0914' })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = '#22242e' })
vim.api.nvim_set_hl(0, 'DiffText', { fg = '#D5D8DA', bg = '#22242e' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#c71726' })

-- Git-specific highlight groups
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#27D797' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#2ee2fa' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#F43E5C' })
vim.api.nvim_set_hl(0, 'GitSignsCurrentLineBlame', { fg = '#666666' })

-- Diagnostic highlight groups
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#F43E5C' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#faf18e' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#6394bf' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#27D797' })

-- Neogit highlight groups
vim.api.nvim_set_hl(0, 'NeogitDiffAddHighlight', { bg = '#14342b' })
vim.api.nvim_set_hl(0, 'NeogitDiffDeleteHighlight', { bg = '#650d1b' })
vim.api.nvim_set_hl(0, 'NeogitDiffContextHighlight', { bg = '#1C1E26' })

-- tresitter
vim.api.nvim_set_hl(0, '@comment', { fg = '#5a554f', italic = true })
vim.api.nvim_set_hl(0, '@comment.tsx', { fg = '#5a554f', italic = true })
vim.api.nvim_set_hl(0, '@punctuation', { fg = '#ac826e' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#a1866f' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#614d40' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#2db889' })
vim.api.nvim_set_hl(0, '@constant.tsx', { fg = '#2db889' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#2db889' })
vim.api.nvim_set_hl(0, '@variable', { fg = '#e9cbb2' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#b38967', italic = true })
vim.api.nvim_set_hl(0, '@function', { fg = '#d86f50' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#c96648' })
vim.api.nvim_set_hl(0, '@function.method', { fg = '#e27554', italic = true, bold = false })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#ce8365', italic = true })
vim.api.nvim_set_hl(0, '@tag', { fg = '#13a570', bold = false, underline = false })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#d68d59', italic = true })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#9a958d', italic = true })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#b16b6b', italic = true })
vim.api.nvim_set_hl(0, '@type', { fg = '#c29a46', italic = true, underline = false })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#b87926', italic = true, underline = false })
vim.api.nvim_set_hl(0, '@type.tsx', { underline = false })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#a8a769' })
vim.api.nvim_set_hl(0, '@string', { fg = '#e98b48' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#62a594' })
vim.api.nvim_set_hl(0, '@string.regex', { fg = '#bb75ac' })
vim.api.nvim_set_hl(0, '@property', { fg = '#be9233', bold = false })
vim.api.nvim_set_hl(0, '@number', { fg = '#d1735b' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#73ac35' })
vim.api.nvim_set_hl(0, '@text.title', { fg = '#da5656' })
vim.api.nvim_set_hl(0, '@text.quote', { fg = '#65737E', italic = true })
vim.api.nvim_set_hl(0, '@text.literal', { fg = '#9aad66' })
vim.api.nvim_set_hl(0, '@text.strong', { fg = '#e9ded7', bold = false })
vim.api.nvim_set_hl(0, '@text.emphasis', { fg = '#ddc2a8', italic = true })
vim.api.nvim_set_hl(0, '@text.uri', { fg = '#5ece91', underline = false })
vim.api.nvim_set_hl(0, '@text.diff.add', { fg = '#C3E88D' })
vim.api.nvim_set_hl(0, '@text.diff.delete', { fg = '#FF5370' })
