-- https://shiki.style/
-- https://github.com/antfu/vscode-theme-vitesse/blob/main/themes/vitesse-dark.json
-- https://github.dev/samharju/synthweave.nvim/blob/master/lua/synthweave/palette.lua
-- https://user-images.githubusercontent.com/11247099/110247187-f1eb6780-7fa5-11eb-9258-620309e20961.png

-- Vitesse Dark theme for Neovim, converted from VSCode theme
-- Core Neovim UI highlight groups
vim.api.nvim_set_hl(0, 'Normal', { fg = '#dbd7ca', bg = '#090909' })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#dbd7ca', bg = '#121212' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#262335' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#576c7d' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#bfbaaa' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#353163' })
vim.api.nvim_set_hl(0, 'Search', { fg = '#72f1b8', reverse = true })
vim.api.nvim_set_hl(0, 'IncSearch', { reverse = true })
vim.api.nvim_set_hl(0, 'MatchParen', { bg = '#4d9375' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#bfbaaa', bg = '#121212' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#959da5', bg = '#121212' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#191919' })
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#959da5', bg = '#121212' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#dbd7ca', bg = '#121212' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#121212' })
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#dbd7ca', bg = '#181818' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#353163' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#dedcd5' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#423e77' })
vim.api.nvim_set_hl(0, 'WildMenu', { fg = '#121212', bg = '#dedcd5' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#dbd7ca', bold = true })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#423e77' })
vim.api.nvim_set_hl(0, 'FoldColumn', { fg = '#dedcd5' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#121212' })
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = '#102922' })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = '#4d0914' })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = '#243345' })
vim.api.nvim_set_hl(0, 'DiffText', { fg = '#ffab70', bg = '#425367' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#d4976c' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#6394bf' })
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'Preproc', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#2e2a4f' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { bg = '#181818' })
vim.api.nvim_set_hl(0, 'Terminal', { fg = '#dbd7ca', bg = '#121212' })

-- Git-specific highlight groups
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#6394bf' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#cb7676' })

-- Diagnostic highlight groups
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#d4976c' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#6394bf' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#4d9375' })

-- Tree-sitter syntax highlight groups (corrected)
vim.api.nvim_set_hl(0, '@comment', { fg = '#758575' })
vim.api.nvim_set_hl(0, '@comment.typescript', { fg = '#515c51' })
vim.api.nvim_set_hl(0, '@punctuation', { fg = '#666666' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#666666' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#666666' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#c99076' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#c99076' })
vim.api.nvim_set_hl(0, '@variable', { fg = '#DF9464' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#c99076' })
vim.api.nvim_set_hl(0, '@function', { fg = '#80a665' })
vim.api.nvim_set_hl(0, '@function_builtin', { fg = '#80a665' })
vim.api.nvim_set_hl(0, '@function.method', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#dbd7ca' })
vim.api.nvim_set_hl(0, '@tag', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, '@keyword.tsx', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, '@keyword.return.tsx', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, '@keyword.typescript', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, '@keyword.type.typescript', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, '@keyword.function.typescript', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, '@type', { fg = '#5d99a9' })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#5d99a9' })
vim.api.nvim_set_hl(0, '@type.javascript', { fg = '#cb7676' })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#db889a' })
vim.api.nvim_set_hl(0, '@string', { fg = '#f39237' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#e6cc77' })
vim.api.nvim_set_hl(0, '@string.regex', { fg = '#c4704f' })
vim.api.nvim_set_hl(0, '@property', { fg = '#b8a965' })
vim.api.nvim_set_hl(0, '@number', { fg = '#4c9a91' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, '@text.title', { fg = '#4d9375', bold = true })
vim.api.nvim_set_hl(0, '@text.quote', { fg = '#5d99a9' })
vim.api.nvim_set_hl(0, '@text.literal', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, '@text.strong', { fg = '#dbd7ca', bold = true })
vim.api.nvim_set_hl(0, '@text.emphasis', { fg = '#dbd7ca', italic = true })
vim.api.nvim_set_hl(0, '@text.uri', { fg = '#c98a7d', underline = true })
vim.api.nvim_set_hl(0, '@text.diff.add', { fg = '#85e89d', bg = '#144620' })
vim.api.nvim_set_hl(0, '@text.diff.delete', { fg = '#fdaeb7', bg = '#86181d' })
vim.api.nvim_set_hl(0, '@error', { fg = '#fdaeb7', italic = true })
vim.api.nvim_set_hl(0, '@attribute', { fg = '#b8a965' })
vim.api.nvim_set_hl(0, '@label', { fg = '#b8a965' })
vim.api.nvim_set_hl(0, '@include', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#80a665' })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#dbd7ca' })
vim.api.nvim_set_hl(0, '@constant.numeric', { fg = '#4c9a91' })
vim.api.nvim_set_hl(0, '@module', { fg = '#cb7676', italic = true })
vim.api.nvim_set_hl(0, '@tag.builtin', { fg = '#4d9375' })
vim.api.nvim_set_hl(0, '@punctuation.bracket.javascript', { fg = '#cb7676' })
